name: Docs

on:
  push:
    tags: 'v*'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docs
        run: |
          pip3 install --upgrade pip
          pip3 install .[dev]
          mkdir -p site/img
          cp docs/img/*.png site/img
          pdoc --math src/deep_unfolding --logo img/logo.png --favicon img/favicon.png -o site
      - name: Deploy to GitHub pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site